### ISSUE TITLE
As an admin I want to be able to add offers to the vendors

### ISSUE THREAD

**Issue by VanJackal** [InternetEnemies/CombatCritters#121]
##### Sharp
- [ ] InternetEnemies/combatcritters-sharp/issues/31
- [ ] InternetEnemies/combatcritters-sharp/issues/32
- [ ] InternetEnemies/combatcritters-sharp/issues/29
- [ ] InternetEnemies/combatcritters-sharp/issues/34
##### MAUI
- [x] internetenemies/combatcritters-maui#31
    - [x] internetenemies/combatcritters-maui#32
- [x] internetenemies/combatcritters-maui#33
    - [x] internetenemies/combatcritters-maui#34
##### API
- [x] #153
- [x] #154
- [x] #155
