### ISSUE TITLE
As a user I want to be able to create a profile

### ISSUE THREAD

**Issue by VanJackal** [InternetEnemies/CombatCritters#16]
### Acceptance Criteria
- Scenario: User attempts to create a new account
    - Given I’m a new user and I’m on the Sign-in page
    - When I fill in the “Username” and “Password” fields with valid information and I click “Create Account” 
    - Then the system creates an account for me and logs me in with my new account
#### React
- [ ] InternetEnemies/combatcritters-react#16
#### ts wrap
- [ ] InternetEnemies/combatcritters-ts#10
#### maui
- [ ] InternetEnemies/combatcritters-maui#6
- [ ] InternetEnemies/combatcritters-maui#8
#### c# wrap
- [ ] InternetEnemies/combatcritters-sharp#7
- [ ] InternetEnemies/combatcritters-sharp#8
#### API
- [x] #28

**Comment by kivine99** [comment]
# React Frontend Acceptance Test

## Register acceptance test

**Assumptions: The username you are registering with is not taken.**

1. Go to  http://localhost:3000/login
2. Click on the "Signup" button/tab
3. Enter a username in the "Username" textbox
4. Enter a password in the "Password" textbox
5. Re-enter the same password in the "Confirm Password" textbox
6. Click on the "Register" button
7. Assert that you are taken to the Collection page

**Comment by idafum** [comment]
# .NET MAUI Frontend Acceptance Test
## Register acceptance test
### Assumptions: The username you are registering is not taken.

1. Given the User is on the login page
2. When the user clicks the "Create Acccount" button
3. Then system should navigate to the create account page
4. Given the user is on the create account page
5. When the user fills in all the required fields (Username, Password)
6. When the user clicks the "Create Account" button
7. Then the system should register the user using the form data
8. Then the system should navigate the user back to the Login Page.

**Comment by idafum** [comment]
# .NET MAUI Frontend Acceptance Test
## Login acceptance test

1. Given the user has created an account
2. Given the user is on the login page
3. When the user fills in all required fields (eg Username, Password)
4. When the user clicks the "Login" button
5. Then the system should navigate the user to the user's "profile page"
