### ISSUE TITLE
As a user I want to feature decks on my profile

### ISSUE THREAD

**Issue by VanJackal** [InternetEnemies/CombatCritters#17]
### Acceptance Criteria
- Scenario: User attempts to share a deck on their deck on their profile
    - Given I’m a signed-in user with a valid deck
    - When I’m on my profile page and click on a valid deck I want to feature on my profile
    - Then said deck is displayed on my profile for my friends to see

### React
- [x] InternetEnemies/combatcritters-react#11
- [x] InternetEnemies/combatcritters-react#12
### TS Wrapper
- [x] InternetEnemies/combatcritters-ts#7

### C# Wrap
- [x] InternetEnemies/combatcritters-sharp#4
### API
- [x] #57
- [x] #58
- [x] #59

**Comment by kivine99** [comment]
# React Frontend Acceptance Test

## Feature deck acceptance test

**Assumptions: You are a logged in user, are on the profile page, and have a deck made.**

1. Click on one of your decks (under the "Feature a Deck on your Profile" section)
2. Assert that the contents of your deck are shown in deck section next to the list
3. Logout (this is currently done by going to http://localhost:3000/login)
4. Log back in with your credentials
5. Navigate to the profile page
6. Assert that the deck you selected is still selected

**Comment by idafum** [comment]
# .NET MAUI Frontend Acceptance Test
## Feature Deck acceptance test
1. Given that you are a logged in user, you are on the profile page
2. When you click on "Deck List" button
3. Then you should see a list containing your deck names
4. Given that you have at least one deck in your deck list
5. When you click on the deck you want to feature from your deck list
6. Then the cards of that deck should be displayed in the featured deck frame.
