### ISSUE TITLE
As a user I want to be able to add friends and accept friend requests

### ISSUE THREAD

**Issue by VanJackal** [InternetEnemies/CombatCritters#18]
### Acceptance Criteria
- Scenario: User attempts to send a friend request
    - Given I’m a signed-in user and I’m on the profile page
    - When I enter a valid username and click “Send Friend Request” 
    - Then the account of the username entered will receive a friend request
- Scenario: User receives notification of a friend request
    - Given I’m a signed-in user and not in a battle and have an incoming friend request
    - Then I want my notifications icon to alert me to the incoming request
- Scenario: User attempts to accept incoming friend request
    - Given I’m a signed-in user and on the incoming friend requests screen and have an incoming friend request
    - When I press the “Accept friend request” button
    - Then I want that friend to be added to my friends list

#### React
- [ ] InternetEnemies/combatcritters-react#9
- [ ] InternetEnemies/combatcritters-react#10

#### TS Wrapper
- [ ] InternetEnemies/combatcritters-ts#3

#### API
- [x] #54 
- [x] #55 
- [x] #56

**Comment by kivine99** [comment]
# React Frontend Acceptance Test
## Adding friend acceptance test

**Assumptions:** You have just logged in as a valid user and have been redirected to the homepage. And you have an incoming friend request.

1. Click on the profile icon in the top right
2. Click on the "Your Profile" button popover that appears below the profile icon
3. Under the incoming friend requests section click on the green checkmark next to the users name
4. Assert that the user who sent the request appears in the your friends section. Also assert that the notifications icon over the profile icon decreases by one

**Comment by kivine99** [comment]
# React Frontend Acceptance Test

## Incoming friend requests notifications

**Assumptions: You are a logged in user, are on the profile page, and have an incoming friend request**

1. Count the number of incoming friend requests under "Incoming friend requests" section and assert that the number in notification icon (located on the top right of the profile icon) matches the number of friend requests you counted

**Comment by kivine99** [comment]
# React Frontend Accpetance Test

## Adding a friend acceptance test

**Assumptions: You have two tabs open and are logged in on both( say as userA and userB). userA is on the profile page and userB is on the collection page.**

1. userA: In the "Send Friend Request" type userB's username and click send
2. userB: click on the profile icon in the top right of the screen and then click on the "Your Profile" button that pops down below the icon
3. userB: assert that in the "Incoming Friend Request" section that you see userA's username
