### ISSUE TITLE
As a user I want to purchase items from digital vendors

### ISSUE THREAD

**Issue by VanJackal** [InternetEnemies/CombatCritters#19]
### Acceptance Criteria
- Scenario: User attempts to purchase an item from a vendor
    - Given I’m a signed in user and I’m in the vendor marketplace and I have the necessary cards/packs/currency to make a trade with a vendor
    - When I click the “Make trade” button on a trade I have the required cards for
    - Then there will be an alert notifying me the trade was successful and the offered cards/packs/currency from the trade will be added to my inventory  and the required cards/packs/currency will be removed from my inventory and the vendor who was being traded with will gain a certain amount of levels

### Description
- Purchasing both cards and packs from vendors
- Specifying the amount of cards and packs I'm purchasing
- Barter offers
##### React
- [x] internetenemies/combatcritters-react/issues/57
- [x] internetenemies/combatcritters-react/issues/58
- [x] internetenemies/combatcritters-react/issues/59
- [x] internetenemies/combatcritters-react/issues/60
- [x] internetenemies/combatcritters-react/issues/61
- [x] internetenemies/combatcritters-react/issues/62

##### TS
- [x] InternetEnemies/combatcritters-ts/issues/65
- [x] InternetEnemies/combatcritters-ts/issues/63
- [x] InternetEnemies/combatcritters-ts/issues/61
- [x] InternetEnemies/combatcritters-ts/issues/66

##### API
- [x] #131
- [x] #132
- [x] #133
- [x] #134
- [x] #135
- [x] #136
- [x] #137
- [x] #138
- [x] #139
- [x] #140
- [x] #141

**Comment by kivine99** [comment]
# React Frontend Acceptance Test
## Purchasing items acceptance test

**Assumptions:** You are logged in  and have the necessary items to make a trade.

1. Click on the vendors button in the navbar
2. Click the vendor "Roberto"
3. Click on the first offer
4. Click deal in the div that appeared
5. Click on "Deck Builder" in the navbar
6. Assert that the card you bought is now in your inventory
