### ISSUE TITLE
As a user I want to level up digital vendors for the opportunity to purchase better items

### ISSUE THREAD

**Issue by VanJackal** [InternetEnemies/CombatCritters#20]
### Acceptance Criteria
- Scenario: Vendor receives enough experience to level-up
    - Given a vendor has received multiple trades
    - When the vendor has received enough experience from the trades that they level up
    - Then that trader should begin offering additional trades
### Desctription
- multiple vendors with xp (gained from purchasing items)
##### React
- [x] internetenemies/combatcritters-react#51
- [x] internetenemies/combatcritters-react/issues/52
##### TS
- [x] InternetEnemies/combatcritters-ts/issues/64
##### MAUI
- [x] internetenemies/combatcritters-maui#29
    - [x] internetenemies/combatcritters-maui#30
##### Sharp
- [x] InternetEnemies/combatcritters-sharp/issues/30
##### API
- [x] #142
- [x] #143
- [x] #144
- [x] #145

**Comment by kivine99** [comment]
# React Frontend Acceptance Test
## Accepting friend request acceptance test

**Assumptions:** You are logged in  and have the necessary items to make a trade.

1. Click on the vendors button in the navbar
2. Click the vendor "Roberto"
3. Click on the first offer
4. Click deal in the div that appeared
5. Assert that the vendor's reputation increases

**Comment by kivine99** [comment]
# React Frontend Acceptance Test
## Accepting friend request acceptance test

**Assumptions:** You are logged in  and have the necessary items to make a trade and are one trade away from levelling Roberto to level 2.

1. Click on the vendors button in the navbar
2. Click the vendor "Roberto"
3. Click on the first offer
4. Click deal in the div that appeared
5. Assert that the vendor's reputation increases to level 2 and assert that a new trade offer appears
