### ISSUE TITLE
As a user I want vendors to have new goods for sale each day

### ISSUE THREAD

**Issue by VanJackal** [InternetEnemies/CombatCritters#21]
### Acceptance Criteria
- Scenario: User attempts to purchase an item from a vendor
    - Given I’m a signed in user and I’m in the vendor marketplace
    - When the vendor’s trades shows up, there should be at least one on-sale trades which vary from 10% off to 80% off
    - The on-sale trades should refresh everyday
    - I should be able to make trade in a cheaper cost with the on-sale trade
### Description
- discounts
- rotating offers (offer may not be available every day)(special offers) 
##### MAUI
- [x] internetenemies/combatcritters-maui#25
    - [x] internetenemies/combatcritters-maui#26
- [x] internetenemies/combatcritters-maui#27
    - [x] internetenemies/combatcritters-maui#28
##### Sharp
- [x] InternetEnemies/combatcritters-sharp/issues/29
##### React
- [x] internetenemies/combatcritters-react/issues/53
- [x] internetenemies/combatcritters-react/issues/54
- [x] internetenemies/combatcritters-react/issues/55
- [x] internetenemies/combatcritters-react/issues/56
##### TS
- [x] InternetEnemies/combatcritters-ts/issues/63
- [x] InternetEnemies/combatcritters-ts/issues/62
##### API
- [x] #146
- [x] #147
- [x] #148
- [x] #149
- [x] #150
