### ISSUE TITLE
as an admin I want to put together new packs for the game

### ISSUE THREAD

**Issue by VanJackal** [InternetEnemies/CombatCritters#33]
#### MAUI
- [x] internetenemies/combatcritters-maui#35
    - [x] internetenemies/combatcritters-maui#36
- [x] internetenemies/combatcritters-maui#37
    - [x] internetenemies/combatcritters-maui#38
#### Sharp
- [x] InternetEnemies/combatcritters-sharp/issues/36
- [x] InternetEnemies/combatcritters-sharp/issues/37
- [x] InternetEnemies/combatcritters-sharp/issues/35
#### API
 - [x] #124
 - [x] #125
 - [x] #126
