### ISSUE TITLE
as a user I want to be able to create (and save)/delete decks

### ISSUE THREAD

**Issue by VanJackal** [InternetEnemies/CombatCritters#42]
#### React
- [ ] internetenemies/combatcritters-react#14
- [x] internetenemies/combatcritters-react#15
#### ts Wrap
- [x] internetenemies/combatcritters-ts#9
- [ ] internetenemies/combatcritters-ts#21
#### API
- [x] #61

**Comment by kivine99** [comment]
# React Frontend Acceptance Test

## Creating deck acceptance test

**Assumptions: You are logged in and on the collection page**

1. Click on the plus icon button
2. In the text-box that pops up, enter your deck name and then click the "Create" button
3. Assert your deck is now the selected deck checking to see if your decks name is displayed in the deck dropdown widget

**Comment by kivine99** [comment]
# React Frontend Acceptance Test

## Deleting deck acceptance test

**Assumptions: You are logged in, on the collection page, and already have a deck made.**

1. Note the name of the deck you currently have selected by looking at the decks dropdown widget
2. Click on the trash icon
3. In the confirmation dialog that pops up, click on confirm
4. Click on the decks dropdown widget and assert that your decks name is no longer in the dropdown list
