### ISSUE TITLE
As a user I want to be able to see the validity of my deck

### ISSUE THREAD

**Issue by VanJackal** [InternetEnemies/CombatCritters#43]
#### React
- [x] internetenemies/combatcritters-react#17
- [x] internetenemies/combatcritters-react#18
#### ts wrap
- [x] internetenemies/combatcritters-ts#9
- [x] internetenemies/combatcritters-ts#11
- [x]  internetenemies/combatcritters-ts#72
#### API
- [x] #63

**Comment by kivine99** [comment]
# React Frontend Acceptance Test

# Invalid indicator acceptance test

**Assumption: You are logged in, on the collection page, have an invalid deck selected.**

1. Assert that in the bottom left area of the deck builder you see a red icon indicating that there are issues with your deck

**Comment by kivine99** [comment]
# React Frontend Acceptance Test

## Valid indicator acceptance test

**Assumption: You are logged in, on the collection page, and have a valid deck selected.**

1. Assert that in the bottom left area of the deck builder you see a green icond indicating that your deck is valid

**Comment by kivine99** [comment]
# React Frontend Acceptance Test

## Issues list acceptance test

*Assumptions: You are logged in, on the collection page, and have an invalid deck selected.**

1. Click on the red icon in the bottom left of your deck builder 
2. Assert that a popup occurs with a list of issues in your deck
