### ISSUE TITLE
As a user I want to browse through my card collection

### ISSUE THREAD

**Issue by VanJackal** [InternetEnemies/CombatCritters#44]
#### React
 - [x] InternetEnemies/combatcritters-react#3
 - [x] InternetEnemies/combatcritters-react#6
#### ts wrapper
- [x] InternetEnemies/combatcritters-ts#12
- [x] InternetEnemies/combatcritters-ts#13
- [x] InternetEnemies/combatcritters-ts#14
#### Maui
- [x] InternetEnemies/combatcritters-maui#10
- [x] InternetEnemies/combatcritters-maui#11
#### c# wrap
- [x] InternetEnemies/combatcritters-sharp#9
- [x] InternetEnemies/combatcritters-sharp#10
- [x] InternetEnemies/combatcritters-sharp#11
#### API
- [x] #64
- [x] #65

**Comment by kivine99** [comment]
# React Frontend Acceptance Test

# Browsing through collection acceptance test

**Assumptions: You are a logged in user, are on the collection page, and have owned cards in your inventory.**

1. Assert that you see cards in your inventory while the "Owned" switch is toggled
