### ISSUE TITLE
as a user i want to view the contents of a pack

### ISSUE THREAD

**Issue by VanJackal** [InternetEnemies/CombatCritters#46]
#### React
- [x] internetenemies/combatcritters-react/issues/63
- [x] internetenemies/combatcritters-react/issues/64
#### TS
- [x] internetenemies/combatcritters-ts/issues/67
#### MAUI
- [x] internetenemies/combatcritters-maui#39
#### Sharp
- [x] InternetEnemies/combatcritters-sharp/issues/35
#### API
- [x] #130

**Comment by kivine99** [comment]
# React Frontend Acceptance Test
## Viewing pack contents acceptance test

**Assumptions:** You are logged in  and have a pack.

1. Click on the Packs button in the navbar
2. Click on your pack
3. Assert that a sidebar pops out displaying the pack set list

**Comment by idafum** [comment]
## MAUI Frontend Acceptance Test
### Viewing Pack contents
#### Assumptions: You are a logged in admin User
1. Given that you are on the "Packs" page
2. When you select a pack from the pack list
3. The system should load the pack image on the right
4. When you click the "open pack" button
5. The system should display a popup of the pack content
