### ISSUE TITLE
as a user I want to view the packs I own

### ISSUE THREAD

**Issue by VanJackal** [InternetEnemies/CombatCritters#48]
#### React
- [x] InternetEnemies/combatcritters-react#49
- [x] Internetenemies/combatcritters-react#50

#### TS
- [x] InternetEnemies/combatcritters-ts/issues/67
- [x] InternetEnemies/combatcritters-ts/issues/68
#### API
- [x] #127
- [x] #128

**Comment by kivine99** [comment]
# React Frontend Acceptance Test
## Viewing packs acceptance test

**Assumptions:** You are logged in  and have packs.

1. Click on the packs button in the navbar
2. Assert that you see packs
