### ISSUE TITLE
As an admin I want to browse and edit all our users profiles

### ISSUE THREAD

**Issue by VanJackal** [InternetEnemies/CombatCritters#53]
#### MAUI
- [x] InternetEnemies/combatcritters-maui#7
- [x] InternetEnemies/combatcritters-maui#9
#### c# wrap
- [x] InternetEnemies/combatcritters-sharp#5
- [x] InternetEnemies/combatcritters-sharp#6
#### API
- [x] #60
- [x] #171

**Comment by sahasra21321** [comment]
Hi, Can i take-up this task.
