### ISSUE TITLE
As a user I want to be able to be matched with an opponent

### ISSUE THREAD

**Issue by VanJackal** [InternetEnemies/CombatCritters#8]
- random matching
- friend matching (only play against friends)

large PLAY button, some way of selecting between: public, friends, ai
### React
- [x] [matching ui](https://github.com/InternetEnemies/combatcritters-react/issues/147)
    - [x] [integrate](https://github.com/InternetEnemies/combatcritters-react/issues/148)
- [x] [waiting for match ui](https://github.com/InternetEnemies/combatcritters-react/issues/149)
    - [x] [integrate](https://github.com/InternetEnemies/combatcritters-react/issues/150)
### TS
- [x] InternetEnemies/combatcritters-ts/issues/128
- [x] InternetEnemies/combatcritters-ts/issues/129
### API
- [x] #229
    - [x] logic
    - [x] data
- [x] #230
- [x] #231

### Acceptance Criteria
- Scenario: User attempts to find an opponent to battle
  - Given I’m a signed in user and I’m on the main screen
  - When I click the “Battle” button
  - Then the system will match me with an opponent who is a similar rank to me
